import { songData } from "../pages/home";

export const DemoSongData: songData[] = [
  {
    _id: 1,
    title: "Song One",
    artist: "Artist A",
    description: "This is a great song by Artist A.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "public/images/image.png",
    category: "Pop",
    duration: 210,
    createdAt: "2024-08-26T08:30:00Z",
    updatedAt: "2024-08-26T08:30:00Z",
  },
  {
    _id: 2,
    title: "Song Two",
    artist: "Artist B",
    description: "A catchy tune by Artist B.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "./public/images/image.png",
    category: "Rock",
    duration: 240,
    createdAt: "2024-08-26T08:35:00Z",
    updatedAt: "2024-08-26T08:35:00Z",
  },
  {
    _id: 3,
    title: "Song Three",
    artist: "Artist C",
    description: "A beautiful ballad by Artist C.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "./public/images/image.png",
    category: "Ballad",
    duration: 300,
    createdAt: "2024-08-26T08:40:00Z",
    updatedAt: "2024-08-26T08:40:00Z",
  },
  {
    _id: 4,
    title: "Song Four",
    artist: "Artist D",
    description: "An upbeat track by Artist D.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "./public/images/image.png",
    category: "Dance",
    duration: 180,
    createdAt: "2024-08-26T08:45:00Z",
    updatedAt: "2024-08-26T08:45:00Z",
  },
  {
    _id: 5,
    title: "Song Five",
    artist: "Artist E",
    description: "A soothing melody by Artist E.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "./public/images/image.png",
    category: "Jazz",
    duration: 270,
    createdAt: "2024-08-26T08:50:00Z",
    updatedAt: "2024-08-26T08:50:00Z",
  },
  {
    _id: 2,
    title: "Song Two",
    artist: "Artist B",
    description: "A catchy tune by Artist B.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "./public/images/image.png",
    category: "Rock",
    duration: 240,
    createdAt: "2024-08-26T08:35:00Z",
    updatedAt: "2024-08-26T08:35:00Z",
  },
  {
    _id: 3,
    title: "Song Three",
    artist: "Artist C",
    description: "A beautiful ballad by Artist C.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "./public/images/image.png",
    category: "Ballad",
    duration: 300,
    createdAt: "2024-08-26T08:40:00Z",
    updatedAt: "2024-08-26T08:40:00Z",
  },
  {
    _id: 4,
    title: "Song Four",
    artist: "Artist D",
    description: "An upbeat track by Artist D.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "./public/images/image.png",
    category: "Dance",
    duration: 180,
    createdAt: "2024-08-26T08:45:00Z",
    updatedAt: "2024-08-26T08:45:00Z",
  },
  {
    _id: 5,
    title: "Song Five",
    artist: "Artist E",
    description: "A soothing melody by Artist E.",
    coverPhotoUrl: "public/images/image.png",
    audioUrl: "./public/images/image.png",
    category: "Jazz",
    duration: 270,
    createdAt: "2024-08-26T08:50:00Z",
    updatedAt: "2024-08-26T08:50:00Z",
  },
];
